[user]
full_name = "Demo Account"
username = "demo"
password_hash = ""
active = true

[tinyexpenses]
currency = "USD"
api_token = "vvHsf3-G__dlytnFQTokU--OCY2rkWrmDAg6FC7K6F8"
dark_color_scheme = true
